import { type Locale, locales } from "../i18n/config";
const copy = {
  originalNotice: [
    "Este artigo tem seis versões. Edita os textos no painel de publicação internacional acima; o editor original continua disponível para artigos manuais.",
    "This article has six versions. Edit the texts in the international publishing panel above; the original editor remains available for manual articles.",
    "Cet article possède six versions. Modifiez les textes dans le panneau de publication internationale ci-dessus ; l’éditeur original reste disponible pour les articles manuels.",
    "Este artículo tiene seis versiones. Edita los textos en el panel de publicación internacional superior; el editor original sigue disponible para artículos manuales.",
    "Dieser Artikel hat sechs Versionen. Bearbeiten Sie die Texte oben im internationalen Veröffentlichungsbereich; der ursprüngliche Editor bleibt für manuelle Artikel verfügbar.",
    "Questo articolo ha sei versioni. Modifica i testi nel pannello di pubblicazione internazionale sopra; l’editor originale resta disponibile per gli articoli manuali.",
  ],
  previous: [
    "Anterior",
    "Previous",
    "Précédent",
    "Anterior",
    "Zurück",
    "Precedente",
  ],
  nextPage: [
    "Seguinte",
    "Next",
    "Suivant",
    "Siguiente",
    "Weiter",
    "Successivo",
  ],
  more: [
    "Carregar mais",
    "Load more",
    "Charger plus",
    "Cargar más",
    "Mehr laden",
    "Carica altro",
  ],
  title: [
    "Publicação internacional",
    "International publishing",
    "Publication internationale",
    "Publicación internacional",
    "Internationale Veröffentlichung",
    "Pubblicazione internazionale",
  ],
  intro: [
    "Um tema a cada 48 horas, com seis versões. As verificações automáticas avaliam estrutura e conteúdo; não certificam a exatidão factual. Artigos sensíveis ficam para revisão humana.",
    "One topic every 48 hours, with six versions. Automated checks assess structure and content; they do not certify factual accuracy. Sensitive articles require human review.",
    "Un sujet toutes les 48 heures, avec six versions. Les contrôles automatiques évaluent la structure et le contenu, sans certifier les faits. Les articles sensibles nécessitent une révision humaine.",
    "Un tema cada 48 horas, con seis versiones. Las comprobaciones automáticas evalúan estructura y contenido; no certifican los hechos. Los artículos sensibles requieren revisión humana.",
    "Ein Thema alle 48 Stunden mit sechs Versionen. Automatische Prüfungen bewerten Struktur und Inhalt, bestätigen aber keine Fakten. Sensible Artikel erfordern menschliche Prüfung.",
    "Un tema ogni 48 ore, con sei versioni. I controlli automatici valutano struttura e contenuto, ma non certificano i fatti. Gli articoli sensibili richiedono revisione umana.",
  ],
  enabled: [
    "Ativar calendário",
    "Enable schedule",
    "Activer le calendrier",
    "Activar calendario",
    "Zeitplan aktivieren",
    "Attivare calendario",
  ],
  auto: [
    "Publicar automaticamente após as verificações",
    "Publish automatically after checks",
    "Publier automatiquement après les contrôles",
    "Publicar automáticamente tras las comprobaciones",
    "Nach Prüfungen automatisch veröffentlichen",
    "Pubblicare automaticamente dopo i controlli",
  ],
  cap: [
    "Limite de pedidos de IA por mês (automação)",
    "Monthly AI request limit (automation)",
    "Limite mensuelle de requêtes IA (automatisation)",
    "Límite mensual de solicitudes IA (automatización)",
    "Monatliches KI-Anfragelimit (Automatisierung)",
    "Limite mensile richieste IA (automazione)",
  ],
  save: ["Guardar", "Save", "Enregistrer", "Guardar", "Speichern", "Salva"],
  refresh: [
    "Atualizar",
    "Refresh",
    "Actualiser",
    "Actualizar",
    "Aktualisieren",
    "Aggiorna",
  ],
  preview: [
    "Gerar seis rascunhos para validar",
    "Generate six drafts for validation",
    "Générer six brouillons pour validation",
    "Generar seis borradores para validar",
    "Sechs Entwürfe zur Prüfung erstellen",
    "Generare sei bozze da validare",
  ],
  next: [
    "Próximo tema a partir de",
    "Next topic from",
    "Prochain sujet à partir du",
    "Próximo tema a partir de",
    "Nächstes Thema ab",
    "Prossimo tema dal",
  ],
  missing: [
    "Falta configurar CRON_SECRET em produção.",
    "Configure CRON_SECRET in production.",
    "Configurer CRON_SECRET en production.",
    "Configura CRON_SECRET en producción.",
    "CRON_SECRET in Produktion konfigurieren.",
    "Configurare CRON_SECRET in produzione.",
  ],
  provider: [
    "Fornecedor de IA indisponível.",
    "AI provider unavailable.",
    "Fournisseur IA indisponible.",
    "Proveedor IA no disponible.",
    "KI-Anbieter nicht verfügbar.",
    "Fornitore IA non disponibile.",
  ],
  usage: [
    "Pedidos reservados este mês",
    "Requests reserved this month",
    "Requêtes réservées ce mois-ci",
    "Solicitudes reservadas este mes",
    "Reservierte Anfragen diesen Monat",
    "Richieste riservate questo mese",
  ],
  budget: [
    "Cada tentativa reserva seis pedidos, incluindo falhas. O limite é conservador. O custo monetário depende dos tokens e dos preços do fornecedor.",
    "Each attempt reserves six requests, including failures. The limit is conservative. Monetary cost depends on tokens and provider prices.",
    "Chaque tentative réserve six requêtes, échecs inclus. Le plafond est prudent. Le coût dépend des tokens et des tarifs du fournisseur.",
    "Cada intento reserva seis solicitudes, incluidos los fallos. El límite es conservador. El coste depende de los tokens y las tarifas del proveedor.",
    "Jeder Versuch reserviert sechs Anfragen, einschließlich Fehlern. Das Limit ist konservativ. Kosten hängen von Tokens und Anbieterpreisen ab.",
    "Ogni tentativo riserva sei richieste, inclusi gli errori. Il limite è prudente. Il costo dipende dai token e dai prezzi del fornitore.",
  ],
  calendar: [
    "Calendário editorial",
    "Editorial calendar",
    "Calendrier éditorial",
    "Calendario editorial",
    "Redaktionskalender",
    "Calendario editoriale",
  ],
  add: [
    "Adicionar tema",
    "Add topic",
    "Ajouter un sujet",
    "Añadir tema",
    "Thema hinzufügen",
    "Aggiungi tema",
  ],
  sources: [
    "Fontes oficiais (um URL por linha)",
    "Official sources (one URL per line)",
    "Sources officielles (une URL par ligne)",
    "Fuentes oficiales (una URL por línea)",
    "Offizielle Quellen (eine URL pro Zeile)",
    "Fonti ufficiali (un URL per riga)",
  ],
  history: [
    "Histórico e versões",
    "History and versions",
    "Historique et versions",
    "Historial y versiones",
    "Verlauf und Versionen",
    "Cronologia e versioni",
  ],
  retry: [
    "Repetir versões em falta",
    "Retry missing versions",
    "Réessayer les versions manquantes",
    "Reintentar versiones pendientes",
    "Fehlende Versionen erneut versuchen",
    "Riprovare le versioni mancanti",
  ],
  review: [
    "Revi as seis versões e as fontes",
    "I reviewed all six versions and sources",
    "J’ai relu les six versions et les sources",
    "He revisado las seis versiones y las fuentes",
    "Ich habe alle sechs Versionen und Quellen geprüft",
    "Ho revisionato tutte le sei versioni e le fonti",
  ],
  publish: [
    "Publicar seis versões",
    "Publish six versions",
    "Publier les six versions",
    "Publicar seis versiones",
    "Sechs Versionen veröffentlichen",
    "Pubblica sei versioni",
  ],
  edit: [
    "Editar versão",
    "Edit version",
    "Modifier la version",
    "Editar versión",
    "Version bearbeiten",
    "Modifica versione",
  ],
  close: ["Fechar", "Close", "Fermer", "Cerrar", "Schließen", "Chiudi"],
  error: [
    "Não foi possível concluir a operação.",
    "The operation could not be completed.",
    "Impossible de terminer cette opération.",
    "No se pudo completar la operación.",
    "Der Vorgang konnte nicht abgeschlossen werden.",
    "Impossibile completare l’operazione.",
  ],
  done: [
    "Operação concluída.",
    "Operation completed.",
    "Opération terminée.",
    "Operación completada.",
    "Vorgang abgeschlossen.",
    "Operazione completata.",
  ],
  titleField: ["Título", "Title", "Titre", "Título", "Titel", "Titolo"],
  excerpt: [
    "Introdução",
    "Introduction",
    "Introduction",
    "Introducción",
    "Einleitung",
    "Introduzione",
  ],
  content: [
    "Conteúdo",
    "Content",
    "Contenu",
    "Contenido",
    "Inhalt",
    "Contenuto",
  ],
  seo_title: [
    "Título SEO",
    "SEO title",
    "Titre SEO",
    "Título SEO",
    "SEO-Titel",
    "Titolo SEO",
  ],
  seo_description: [
    "Descrição SEO",
    "SEO description",
    "Description SEO",
    "Descripción SEO",
    "SEO-Beschreibung",
    "Descrizione SEO",
  ],
  empty: [
    "Nenhuma execução.",
    "No runs yet.",
    "Aucune exécution.",
    "Ninguna ejecución.",
    "Noch keine Ausführungen.",
    "Nessuna esecuzione.",
  ],
  published: [
    "Publicado",
    "Published",
    "Publié",
    "Publicado",
    "Veröffentlicht",
    "Pubblicato",
  ],
  failed: [
    "Falhou",
    "Failed",
    "Échec",
    "Falló",
    "Fehlgeschlagen",
    "Non riuscito",
  ],
  running: [
    "Em execução",
    "Running",
    "En cours",
    "En ejecución",
    "Läuft",
    "In corso",
  ],
  queued: [
    "Pendente",
    "Queued",
    "En attente",
    "Pendiente",
    "Ausstehend",
    "In attesa",
  ],
  reviewState: [
    "Revisão humana",
    "Human review",
    "Révision humaine",
    "Revisión humana",
    "Menschliche Prüfung",
    "Revisione umana",
  ],
  candidate: [
    "Candidatos",
    "Candidates",
    "Candidats",
    "Candidatos",
    "Bewerbende",
    "Candidati",
  ],
  company: [
    "Empresas",
    "Companies",
    "Entreprises",
    "Empresas",
    "Unternehmen",
    "Aziende",
  ],
  everyone: ["Todos", "Everyone", "Tous", "Todos", "Alle", "Tutti"],
  sensitive: [
    "Precisa de revisão humana",
    "Requires human review",
    "Nécessite une révision humaine",
    "Requiere revisión humana",
    "Menschliche Prüfung erforderlich",
    "Richiede revisione umana",
  ],
  held: [
    "Artigo guardado para revisão; não foi publicado.",
    "Article saved for review; it was not published.",
    "Article enregistré pour révision ; il n’est pas publié.",
    "Artículo guardado para revisión; no se ha publicado.",
    "Artikel zur Prüfung gespeichert; nicht veröffentlicht.",
    "Articolo salvato per revisione; non pubblicato.",
  ],
  category: [
    "Categoria",
    "Category",
    "Catégorie",
    "Categoría",
    "Kategorie",
    "Categoria",
  ],
} satisfies Record<string, readonly string[]>;
export type AcademyCopyKey = keyof typeof copy;
export function academyCopy(locale: Locale, key: AcademyCopyKey) {
  return copy[key][locales.indexOf(locale)];
}
