import { type Locale, locales } from "../i18n/config";
const copy = {
  approvalRequired: [
    "Todos os artigos ficam em rascunho até serem aprovados por um administrador. O administrador recebe um email quando o artigo está pronto para revisão.",
    "Every article remains a draft until an administrator approves it. The administrator receives an email when it is ready for review.",
    "Chaque article reste en brouillon jusqu’à son approbation par un administrateur, averti par email lorsque l’article est prêt à être relu.",
    "Todos los artículos quedan como borrador hasta que un administrador los apruebe. El administrador recibe un email cuando están listos para revisar.",
    "Alle Artikel bleiben Entwürfe, bis sie von einem Administrator freigegeben werden. Sobald ein Artikel zur Prüfung bereit ist, wird der Administrator per E-Mail benachrichtigt.",
    "Tutti gli articoli restano in bozza fino all’approvazione di un amministratore, che riceve un’email quando sono pronti per la revisione.",
  ],
  publicationEmails: [
    "A aprovação publica o artigo e inicia o envio de um email às contas ativas, respeitando as preferências de notificação. Editar ou voltar a publicar o mesmo artigo não repete o envio.",
    "Approval publishes the article and starts emailing active accounts, respecting notification preferences. Editing or republishing the same article does not send it again.",
    "L’approbation publie l’article et lance l’envoi aux comptes actifs, selon leurs préférences. Modifier ou republier le même article ne répète pas l’envoi.",
    "La aprobación publica el artículo e inicia el envío a las cuentas activas, respetando sus preferencias. Editar o volver a publicar el mismo artículo no repite el envío.",
    "Die Freigabe veröffentlicht den Artikel und startet den E-Mail-Versand an aktive Konten gemäß ihren Einstellungen. Bearbeitungen oder erneute Veröffentlichungen lösen keinen weiteren Versand aus.",
    "L’approvazione pubblica l’articolo e avvia l’invio agli account attivi, rispettando le preferenze. Modificare o ripubblicare lo stesso articolo non ripete l’invio.",
  ],
  publicationConfirm: ["Aprovar e publicar este artigo? Será enviado um email às contas ativas que recebem novidades da Academy.", "Approve and publish this article? Active accounts subscribed to Academy updates will receive an email.", "Approuver et publier cet article ? Les comptes actifs abonnés aux nouveautés Academy recevront un email.", "¿Aprobar y publicar este artículo? Las cuentas activas suscritas a las novedades de Academy recibirán un email.", "Diesen Artikel freigeben und veröffentlichen? Aktive Konten mit Academy-Updates erhalten eine E-Mail.", "Approvare e pubblicare questo articolo? Gli account attivi iscritti agli aggiornamenti Academy riceveranno un’email."],
  emailMissing: ["O envio de emails ainda não está configurado.", "Email delivery is not configured yet.", "L’envoi d’emails n’est pas encore configuré.", "El envío de emails aún no está configurado.", "Der E-Mail-Versand ist noch nicht eingerichtet.", "L’invio di email non è ancora configurato."],
  emailPending: ["Emails por enviar", "Emails pending", "Emails en attente", "Emails pendientes", "Ausstehende E-Mails", "Email in attesa"],
  emailSent: ["Aceites pelo serviço de email", "Accepted by email provider", "Acceptés par le service email", "Aceptados por el servicio de email", "Vom E-Mail-Dienst angenommen", "Accettate dal servizio email"],
  emailAttention: ["Envios a verificar", "Deliveries requiring review", "Envois à vérifier", "Envíos por revisar", "Zu prüfende Sendungen", "Invii da verificare"],
  updatesTitle: ["Novos artigos da Academy", "New Academy articles", "Nouveaux articles Academy", "Nuevos artículos de Academy", "Neue Academy-Artikel", "Nuovi articoli Academy"],
  updatesDescription: ["Receber um email quando um novo artigo é aprovado e publicado na Academy.", "Receive an email when a new article is approved and published in the Academy.", "Recevoir un email lorsqu’un nouvel article est approuvé et publié dans l’Academy.", "Recibir un email cuando se apruebe y publique un nuevo artículo en Academy.", "Eine E-Mail erhalten, wenn ein neuer Artikel freigegeben und in der Academy veröffentlicht wird.", "Ricevere un’email quando un nuovo articolo viene approvato e pubblicato nell’Academy."],
  originalNotice: [
    "Este artigo tem seis versões. Edita os textos no painel de publicação internacional acima; o editor original continua disponível para artigos manuais.",
    "This article has six versions. Edit the texts in the international publishing panel above; the original editor remains available for manual articles.",
    "Cet article possède six versions. Modifiez les textes dans le panneau de publication internationale ci-dessus ; l’éditeur original reste disponible pour les articles manuels.",
    "Este artículo tiene seis versiones. Edita los textos en el panel de publicación internacional superior; el editor original sigue disponible para artículos manuales.",
    "Dieser Artikel hat sechs Versionen. Bearbeiten Sie die Texte oben im internationalen Veröffentlichungsbereich; der ursprüngliche Editor bleibt für manuelle Artikel verfügbar.",
    "Questo articolo ha sei versioni. Modifica i testi nel pannello di pubblicazione internazionale sopra; l’editor originale resta disponibile per gli articoli manuali.",
  ],
  previous: [
    "Anterior",
    "Previous",
    "Précédent",
    "Anterior",
    "Zurück",
    "Precedente",
  ],
  nextPage: [
    "Seguinte",
    "Next",
    "Suivant",
    "Siguiente",
    "Weiter",
    "Successivo",
  ],
  more: [
    "Carregar mais",
    "Load more",
    "Charger plus",
    "Cargar más",
    "Mehr laden",
    "Carica altro",
  ],
  title: [
    "Publicação internacional",
    "International publishing",
    "Publication internationale",
    "Publicación internacional",
    "Internationale Veröffentlichung",
    "Pubblicazione internazionale",
  ],
  intro: [
    "Um tema a cada 48 horas, com seis versões. As verificações automáticas avaliam estrutura e conteúdo; não certificam a exatidão factual. Todos os artigos exigem aprovação de um administrador.",
    "One topic every 48 hours, with six versions. Automated checks assess structure and content; they do not certify factual accuracy. All articles require administrator approval.",
    "Un sujet toutes les 48 heures, avec six versions. Les contrôles automatiques évaluent la structure et le contenu, sans certifier les faits. Tous les articles nécessitent l’approbation d’un administrateur.",
    "Un tema cada 48 horas, con seis versiones. Las comprobaciones automáticas evalúan estructura y contenido; no certifican los hechos. Todos los artículos requieren la aprobación de un administrador.",
    "Ein Thema alle 48 Stunden mit sechs Versionen. Automatische Prüfungen bewerten Struktur und Inhalt, bestätigen aber keine Fakten. Alle Artikel müssen von einem Administrator freigegeben werden.",
    "Un tema ogni 48 ore, con sei versioni. I controlli automatici valutano struttura e contenuto, ma non certificano i fatti. Tutti gli articoli richiedono l’approvazione di un amministratore.",
  ],
  enabled: [
    "Ativar calendário",
    "Enable schedule",
    "Activer le calendrier",
    "Activar calendario",
    "Zeitplan aktivieren",
    "Attivare calendario",
  ],
  auto: [
    "Publicar automaticamente após as verificações",
    "Publish automatically after checks",
    "Publier automatiquement après les contrôles",
    "Publicar automáticamente tras las comprobaciones",
    "Nach Prüfungen automatisch veröffentlichen",
    "Pubblicare automaticamente dopo i controlli",
  ],
  cap: [
    "Limite de pedidos de IA por mês (automação)",
    "Monthly AI request limit (automation)",
    "Limite mensuelle de requêtes IA (automatisation)",
    "Límite mensual de solicitudes IA (automatización)",
    "Monatliches KI-Anfragelimit (Automatisierung)",
    "Limite mensile richieste IA (automazione)",
  ],
  save: ["Guardar", "Save", "Enregistrer", "Guardar", "Speichern", "Salva"],
  refresh: [
    "Atualizar",
    "Refresh",
    "Actualiser",
    "Actualizar",
    "Aktualisieren",
    "Aggiorna",
  ],
  preview: [
    "Gerar seis rascunhos para validar",
    "Generate six drafts for validation",
    "Générer six brouillons pour validation",
    "Generar seis borradores para validar",
    "Sechs Entwürfe zur Prüfung erstellen",
    "Generare sei bozze da validare",
  ],
  next: [
    "Próximo tema a partir de",
    "Next topic from",
    "Prochain sujet à partir du",
    "Próximo tema a partir de",
    "Nächstes Thema ab",
    "Prossimo tema dal",
  ],
  missing: [
    "Falta configurar CRON_SECRET em produção.",
    "Configure CRON_SECRET in production.",
    "Configurer CRON_SECRET en production.",
    "Configura CRON_SECRET en producción.",
    "CRON_SECRET in Produktion konfigurieren.",
    "Configurare CRON_SECRET in produzione.",
  ],
  provider: [
    "Fornecedor de IA indisponível.",
    "AI provider unavailable.",
    "Fournisseur IA indisponible.",
    "Proveedor IA no disponible.",
    "KI-Anbieter nicht verfügbar.",
    "Fornitore IA non disponibile.",
  ],
  usage: [
    "Pedidos reservados este mês",
    "Requests reserved this month",
    "Requêtes réservées ce mois-ci",
    "Solicitudes reservadas este mes",
    "Reservierte Anfragen diesen Monat",
    "Richieste riservate questo mese",
  ],
  budget: [
    "Cada tentativa reserva seis pedidos, incluindo falhas. O limite é conservador. O custo monetário depende dos tokens e dos preços do fornecedor.",
    "Each attempt reserves six requests, including failures. The limit is conservative. Monetary cost depends on tokens and provider prices.",
    "Chaque tentative réserve six requêtes, échecs inclus. Le plafond est prudent. Le coût dépend des tokens et des tarifs du fournisseur.",
    "Cada intento reserva seis solicitudes, incluidos los fallos. El límite es conservador. El coste depende de los tokens y las tarifas del proveedor.",
    "Jeder Versuch reserviert sechs Anfragen, einschließlich Fehlern. Das Limit ist konservativ. Kosten hängen von Tokens und Anbieterpreisen ab.",
    "Ogni tentativo riserva sei richieste, inclusi gli errori. Il limite è prudente. Il costo dipende dai token e dai prezzi del fornitore.",
  ],
  calendar: [
    "Calendário editorial",
    "Editorial calendar",
    "Calendrier éditorial",
    "Calendario editorial",
    "Redaktionskalender",
    "Calendario editoriale",
  ],
  add: [
    "Adicionar tema",
    "Add topic",
    "Ajouter un sujet",
    "Añadir tema",
    "Thema hinzufügen",
    "Aggiungi tema",
  ],
  sources: [
    "Fontes oficiais (um URL por linha)",
    "Official sources (one URL per line)",
    "Sources officielles (une URL par ligne)",
    "Fuentes oficiales (una URL por línea)",
    "Offizielle Quellen (eine URL pro Zeile)",
    "Fonti ufficiali (un URL per riga)",
  ],
  history: [
    "Histórico e versões",
    "History and versions",
    "Historique et versions",
    "Historial y versiones",
    "Verlauf und Versionen",
    "Cronologia e versioni",
  ],
  retry: [
    "Repetir versões em falta",
    "Retry missing versions",
    "Réessayer les versions manquantes",
    "Reintentar versiones pendientes",
    "Fehlende Versionen erneut versuchen",
    "Riprovare le versioni mancanti",
  ],
  review: [
    "Revi as seis versões e as fontes",
    "I reviewed all six versions and sources",
    "J’ai relu les six versions et les sources",
    "He revisado las seis versiones y las fuentes",
    "Ich habe alle sechs Versionen und Quellen geprüft",
    "Ho revisionato tutte le sei versioni e le fonti",
  ],
  publish: [
    "Aprovar e publicar seis versões",
    "Approve and publish six versions",
    "Approuver et publier les six versions",
    "Aprobar y publicar seis versiones",
    "Sechs Versionen freigeben und veröffentlichen",
    "Approva e pubblica sei versioni",
  ],
  edit: [
    "Editar versão",
    "Edit version",
    "Modifier la version",
    "Editar versión",
    "Version bearbeiten",
    "Modifica versione",
  ],
  close: ["Fechar", "Close", "Fermer", "Cerrar", "Schließen", "Chiudi"],
  error: [
    "Não foi possível concluir a operação.",
    "The operation could not be completed.",
    "Impossible de terminer cette opération.",
    "No se pudo completar la operación.",
    "Der Vorgang konnte nicht abgeschlossen werden.",
    "Impossibile completare l’operazione.",
  ],
  done: [
    "Operação concluída.",
    "Operation completed.",
    "Opération terminée.",
    "Operación completada.",
    "Vorgang abgeschlossen.",
    "Operazione completata.",
  ],
  titleField: ["Título", "Title", "Titre", "Título", "Titel", "Titolo"],
  excerpt: [
    "Introdução",
    "Introduction",
    "Introduction",
    "Introducción",
    "Einleitung",
    "Introduzione",
  ],
  content: [
    "Conteúdo",
    "Content",
    "Contenu",
    "Contenido",
    "Inhalt",
    "Contenuto",
  ],
  seo_title: [
    "Título SEO",
    "SEO title",
    "Titre SEO",
    "Título SEO",
    "SEO-Titel",
    "Titolo SEO",
  ],
  seo_description: [
    "Descrição SEO",
    "SEO description",
    "Description SEO",
    "Descripción SEO",
    "SEO-Beschreibung",
    "Descrizione SEO",
  ],
  empty: [
    "Nenhuma execução.",
    "No runs yet.",
    "Aucune exécution.",
    "Ninguna ejecución.",
    "Noch keine Ausführungen.",
    "Nessuna esecuzione.",
  ],
  published: [
    "Publicado",
    "Published",
    "Publié",
    "Publicado",
    "Veröffentlicht",
    "Pubblicato",
  ],
  failed: [
    "Falhou",
    "Failed",
    "Échec",
    "Falló",
    "Fehlgeschlagen",
    "Non riuscito",
  ],
  running: [
    "Em execução",
    "Running",
    "En cours",
    "En ejecución",
    "Läuft",
    "In corso",
  ],
  queued: [
    "Pendente",
    "Queued",
    "En attente",
    "Pendiente",
    "Ausstehend",
    "In attesa",
  ],
  reviewState: [
    "Revisão humana",
    "Human review",
    "Révision humaine",
    "Revisión humana",
    "Menschliche Prüfung",
    "Revisione umana",
  ],
  candidate: [
    "Candidatos",
    "Candidates",
    "Candidats",
    "Candidatos",
    "Bewerbende",
    "Candidati",
  ],
  company: [
    "Empresas",
    "Companies",
    "Entreprises",
    "Empresas",
    "Unternehmen",
    "Aziende",
  ],
  everyone: ["Todos", "Everyone", "Tous", "Todos", "Alle", "Tutti"],
  sensitive: [
    "Precisa de revisão humana",
    "Requires human review",
    "Nécessite une révision humaine",
    "Requiere revisión humana",
    "Menschliche Prüfung erforderlich",
    "Richiede revisione umana",
  ],
  held: [
    "Artigo guardado para revisão; não foi publicado.",
    "Article saved for review; it was not published.",
    "Article enregistré pour révision ; il n’est pas publié.",
    "Artículo guardado para revisión; no se ha publicado.",
    "Artikel zur Prüfung gespeichert; nicht veröffentlicht.",
    "Articolo salvato per revisione; non pubblicato.",
  ],
  category: [
    "Categoria",
    "Category",
    "Catégorie",
    "Categoría",
    "Kategorie",
    "Categoria",
  ],
} satisfies Record<string, readonly string[]>;
export type AcademyCopyKey = keyof typeof copy;
export function academyCopy(locale: Locale, key: AcademyCopyKey) {
  return copy[key][locales.indexOf(locale)];
}
