import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';
const admin='10000000-0000-0000-0000-000000000001', candidate='20000000-0000-0000-0000-000000000001', company='30000000-0000-0000-0000-000000000001';
test('account administration: RLS, RPC guard, authority, retries, reactivation and deletion',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create role authenticator;
 create schema auth;create schema private;create schema storage;
 create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
 create table auth.users(id uuid primary key,email text,banned_until timestamptz);
 create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role text);
 create table public.company_profiles(id uuid primary key,user_id uuid references public.profiles(id) on delete cascade);
 create table public.student_profiles(id uuid primary key,user_id uuid references public.profiles(id) on delete cascade,headline text,contact_visibility text,location text,desired_area text);
 create table public.jobs(id uuid primary key,company_id uuid references public.company_profiles(id) on delete cascade,is_active boolean);
 create table public.applications(student_id uuid,job_id uuid);
 create table public.candidate_contact_requests(student_id uuid,job_id uuid,company_id uuid,status text);
 create function public.can_company_read_student_profile(uuid) returns boolean language sql as 'select false';
 create function public.company_candidate_snapshots(uuid[]) returns setof jsonb language sql as 'select jsonb_build_object(''id'',id) from public.student_profiles where id=any($1)';
 create table storage.objects(id uuid);
 alter table public.profiles enable row level security;alter table storage.objects enable row level security;
 create policy own on public.profiles to authenticated using(id=auth.uid());
 create policy own on storage.objects to authenticated using(true) with check(true);
 grant usage on schema public,auth,storage to anon,authenticated,service_role;
 grant select on public.profiles,storage.objects to authenticated;
 insert into auth.users(id,email) values('${admin}','admin@example.invalid'),('${candidate}','candidate@example.invalid'),('${company}','company@example.invalid');
 insert into public.profiles values('${admin}','admin'),('${candidate}','student'),('${company}','company');
 insert into public.company_profiles values('${company}','${company}');
 insert into public.student_profiles values('${candidate}','${candidate}','Engineer','approval_required','Lisboa','Engineering');
 insert into public.jobs values('${company}','${company}',true);
 insert into storage.objects values('${candidate}');`);
 await db.exec(await readFile(new URL('../supabase/migrations/20261002233000_account_administration.sql',import.meta.url),'utf8'));
 await db.exec(`set role authenticated;set request.test_user='${candidate}';`);
 assert.equal((await db.query('select * from public.profiles')).rows.length,1);
 await assert.rejects(db.query(`select public.begin_account_operation('${candidate}','${company}','suspend','Testing','company@example.invalid')`),/permission denied/);
 await assert.rejects(db.query(`select public.registration_status('candidate@example.invalid',repeat('a',64))`),/permission denied/);
 await db.exec('reset role;set role service_role;');
 for(const actor of [candidate,company]) await assert.rejects(db.query(`select public.begin_account_operation('${actor}','${candidate}','suspend','Testing','candidate@example.invalid')`));
 await assert.rejects(db.query(`select public.begin_account_operation('${admin}','${admin}','delete','Testing','admin@example.invalid')`));
 await assert.rejects(db.query(`select public.begin_account_operation('${admin}','${candidate}','delete','Testing','wrong@example.invalid')`));
 const begin=async(action,target=candidate,email='candidate@example.invalid')=>(await db.query(`select public.begin_account_operation('${admin}','${target}','${action}','Testing operation','${email}') as id`)).rows[0].id;
 const finish=async(id,ok=true)=>db.query(`select public.finish_account_operation('${id}',${ok})`);
 const op=await begin('suspend');
 await assert.rejects(begin('delete'),/already running/);
 await finish(op);
 await db.exec(`reset role;set role authenticated;set request.test_user='${candidate}';`);
 assert.equal((await db.query('select * from public.profiles')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.query('select public.check_account_request()'),/suspensa/);
 await db.exec(`set request.test_user='${company}';`);
 assert.equal((await db.query('select public.company_candidate_directory() as data')).rows[0].data.total,0);
 await db.exec('reset role;set role service_role;');
 await finish(await begin('restore'));
 const comp=await begin('suspend',company,'company@example.invalid');await finish(comp);
 await db.exec('reset role;');
 assert.equal((await db.query('select is_active from public.jobs')).rows[0].is_active,false);
 await db.exec(`set role authenticated;set request.test_user='${candidate}';`);
 assert.equal((await db.query('select * from public.profiles')).rows.length,1);
 await db.exec('reset role;set role service_role;');
 const del=await begin('delete');await finish(del,false);
 await assert.rejects(begin('restore'),/Deletion must/);
 const retry=await begin('delete');await db.exec(`reset role;delete from auth.users where id='${candidate}';set role service_role;`);await finish(retry);
 await db.exec(`reset role;set role authenticated;set request.test_user='${candidate}';`);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.query('select public.check_account_request()'),/suspensa/);
 await db.exec('reset role;set role service_role;');
 for(let i=0;i<15;i++)assert.equal((await db.query(`select public.registration_status(' COMPANY@example.invalid ',repeat('a',64)) as data`)).rows[0].data.exists,true);
 assert.equal((await db.query(`select public.registration_status('new@example.invalid',repeat('a',64)) as data`)).rows[0].data.limited,true);
 assert.equal((await db.query(`select public.registration_status('new@example.invalid',repeat('b',64)) as data`)).rows[0].data.exists,false);
 }finally{await db.close();}
});
