import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('candidate consent, company isolation, CV and logo policies', async () => {
 const db = new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
  create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
  create function storage.foldername(text) returns text[] language sql as 'select string_to_array($1,''/'')';
  grant usage on schema public,auth,storage to authenticated;
  create table profiles(id uuid,role text,name text,email text);
  create table company_profiles(id uuid,user_id uuid);
  create table student_profiles(id uuid,user_id uuid,headline text,location text,desired_area text,seniority text,work_model text,talent_type text,contact_visibility text,cv_url text,bio text);
  create table jobs(id uuid,company_id uuid);
  create table ai_matches(student_id uuid,job_id uuid);
  create table applications(id uuid,student_id uuid,job_id uuid,status text);
  create table candidate_contact_requests(id uuid default gen_random_uuid(),company_id uuid,student_id uuid,job_id uuid,status text,message text,created_at timestamptz default now(),updated_at timestamptz default now());
  create table storage.buckets(id text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
  alter table student_profiles enable row level security;
  alter table storage.objects enable row level security;
  create function can_company_read_student_profile(uuid) returns boolean language sql as 'select true';
  create policy full_profiles on student_profiles for select to authenticated using(can_company_read_student_profile(id));
  create policy own_profiles on student_profiles for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
  create policy "Authenticated users can upload company logos" on storage.objects for insert to authenticated with check(bucket_id='company-logos');
  create policy "Authenticated users can update company logos" on storage.objects for update to authenticated using(bucket_id='company-logos');
  create policy "Authenticated users can delete company logos" on storage.objects for delete to authenticated using(bucket_id='company-logos');
  create policy logos_read on storage.objects for select to authenticated using(bucket_id='company-logos');
  grant all on all tables in schema public,storage to authenticated;
  insert into profiles values('${id(1)}','company','A','a@example.invalid'),('${id(2)}','company','B','b@example.invalid'),('${id(3)}','student','Candidate','private@example.invalid');
  insert into company_profiles values('${id(11)}','${id(1)}'),('${id(12)}','${id(2)}');
  insert into jobs values('${id(21)}','${id(11)}'),('${id(22)}','${id(12)}');
  insert into student_profiles values('${id(31)}','${id(3)}','Role','Porto','IT','senior','remote','professional','approval_required','${id(3)}/cv.pdf','Private biography');
  insert into ai_matches values('${id(31)}','${id(21)}');
  insert into storage.objects(bucket_id,name) values('student-cvs','${id(3)}/cv.pdf'),('company-logos','${id(12)}/logo.png');
  insert into storage.buckets(id,public) values('student-cvs',false),('cvs',false),('company-logos',true);
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20260929232747_protect_candidate_privacy.sql',import.meta.url),'utf8'));
  const login = async n => db.exec(`reset role;set role authenticated;set request.test_user='${id(n)}';`);
  const visible = async () => (await db.query('select * from student_profiles')).rows.length;
  await login(1); assert.equal(await visible(),0);
  const preview = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(preview.headline,'Role'); assert.equal(preview.profiles,null); assert.equal(preview.bio,undefined); assert.equal(preview.cv_url,undefined);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(22)}','pending')`),/not authorized/);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','accepted')`),/Only the candidate/);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`);
  await assert.rejects(db.exec("update candidate_contact_requests set status='accepted'"),/Only the candidate/);
  await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(12)}/forged.png')`),/row-level security/);
  await db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(11)}/own.png')`);
  await db.exec(`update storage.objects set name='${id(12)}/edited.png' where name='${id(12)}/logo.png'`);
  assert.equal((await db.query(`select name from storage.objects where name='${id(12)}/logo.png'`)).rows.length,1);
  await login(3); await assert.rejects(db.exec(`update candidate_contact_requests set job_id='${id(22)}'`),/immutable/);
  await db.exec("update candidate_contact_requests set status='accepted'");
  await assert.rejects(db.exec("update candidate_contact_requests set status='rejected'"),/Invalid contact/);
  await login(1); assert.equal(await visible(),1);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,1);
  const full = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(full.profiles.email,'private@example.invalid');
  await login(2); assert.equal(await visible(),0);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await login(3); await db.exec("update student_profiles set contact_visibility='closed'");
  await login(1); assert.equal(await visible(),0);
  await db.exec('reset role'); await db.exec(`insert into applications values('${id(41)}','${id(31)}','${id(21)}','pending')`);
  await login(1); assert.equal(await visible(),1);
  await assert.rejects(db.exec(`update applications set student_id='${id(99)}'`),/permission denied/);
  await db.exec("update applications set status='accepted'");
  await db.exec('reset role'); await db.exec('delete from applications');
  await login(3); await db.exec("update student_profiles set contact_visibility='open'");
  await login(1); assert.equal(await visible(),1);
  await login(2); assert.equal(await visible(),0);
 } finally { await db.close(); }
});
