import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('candidate consent, company isolation, CV and logo policies', async () => {
 const db = new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
  create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
  create function storage.foldername(text) returns text[] language sql as 'select string_to_array($1,''/'')';
  grant usage on schema public,auth,storage to authenticated;
  create table profiles(id uuid,role text,name text,email text);
  create table company_profiles(id uuid,user_id uuid);
  create table student_profiles(id uuid,user_id uuid,headline text,location text,desired_area text,seniority text,work_model text,talent_type text,contact_visibility text,cv_url text,bio text);
  create table jobs(id uuid,company_id uuid);
  create table ai_matches(student_id uuid,job_id uuid);
  create table applications(id uuid,student_id uuid,job_id uuid,status text);
  create table candidate_contact_requests(id uuid default gen_random_uuid(),company_id uuid,student_id uuid,job_id uuid,status text,message text,created_at timestamptz default now(),updated_at timestamptz default now());
  create table storage.buckets(id text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
  alter table student_profiles enable row level security;
  alter table storage.objects enable row level security;
  create function can_company_read_student_profile(uuid) returns boolean language sql as 'select true';
  create policy full_profiles on student_profiles for select to authenticated using(can_company_read_student_profile(id));
  create policy own_profiles on student_profiles for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
  create policy "Authenticated users can upload company logos" on storage.objects for insert to authenticated with check(bucket_id='company-logos');
  create policy "Authenticated users can update company logos" on storage.objects for update to authenticated using(bucket_id='company-logos');
  create policy "Authenticated users can delete company logos" on storage.objects for delete to authenticated using(bucket_id='company-logos');
  create policy logos_read on storage.objects for select to authenticated using(bucket_id='company-logos');
  grant all on all tables in schema public,storage to authenticated;
  insert into profiles values('${id(1)}','company','A','a@example.invalid'),('${id(2)}','company','B','b@example.invalid'),('${id(3)}','student','Candidate','private@example.invalid');
  insert into company_profiles values('${id(11)}','${id(1)}'),('${id(12)}','${id(2)}');
  insert into jobs values('${id(21)}','${id(11)}'),('${id(22)}','${id(12)}');
  insert into student_profiles values('${id(31)}','${id(3)}','Role','Porto','IT','senior','remote','professional','approval_required','${id(3)}/cv.pdf','Private biography');
  insert into ai_matches values('${id(31)}','${id(21)}');
  insert into storage.objects(bucket_id,name) values('student-cvs','${id(3)}/cv.pdf'),('company-logos','${id(12)}/logo.png');
  insert into storage.buckets(id,public) values('student-cvs',false),('cvs',false),('company-logos',true);
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20260929232747_protect_candidate_privacy.sql',import.meta.url),'utf8'));
  const migration = (await readdir(new URL('../supabase/migrations/',import.meta.url))).find(name=>name.endsWith('_allow_owned_company_candidate_reads.sql'));
  assert.ok(migration,'owned-company read migration must be present');
  await db.exec(await readFile(new URL(`../supabase/migrations/${migration}`,import.meta.url),'utf8'));
  const login = async n => db.exec(`reset role;set role authenticated;set request.test_user='${id(n)}';`);
  const visible = async () => (await db.query('select * from student_profiles')).rows.length;
  await login(1); assert.equal(await visible(),0);
  const preview = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(preview.headline,'Role'); assert.equal(preview.profiles,null); assert.equal(preview.bio,undefined); assert.equal(preview.cv_url,undefined);
  await db.exec('reset role');
  await db.exec(`update profiles set role='admin' where id='${id(1)}'; insert into profiles values('${id(4)}','admin','Unassociated admin','admin@example.invalid');`);
  await login(1);
  assert.equal(await visible(),0,'admin company owner still needs candidate consent');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null);
  await login(4);
  assert.equal(await visible(),0,'admin without a company gets no global candidate access');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  await db.exec('reset role'); await db.exec(`update profiles set role='company' where id='${id(1)}'`);
  await login(1);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(22)}','pending')`),/not authorized/);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','accepted')`),/Only the candidate/);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`);
  await assert.rejects(db.exec("update candidate_contact_requests set status='accepted'"),/Only the candidate/);
  await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(12)}/forged.png')`),/row-level security/);
  await db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(11)}/own.png')`);
  await db.exec(`update storage.objects set name='${id(12)}/edited.png' where name='${id(12)}/logo.png'`);
  assert.equal((await db.query(`select name from storage.objects where name='${id(12)}/logo.png'`)).rows.length,1);
  await login(3); await assert.rejects(db.exec(`update candidate_contact_requests set job_id='${id(22)}'`),/immutable/);
  await db.exec("update candidate_contact_requests set status='accepted'");
  await assert.rejects(db.exec("update candidate_contact_requests set status='rejected'"),/Invalid contact/);
  await login(1); assert.equal(await visible(),1);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,1);
  const full = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(full.profiles.email,'private@example.invalid');
  await db.exec('reset role'); await db.exec(`update profiles set role='admin' where id='${id(1)}'`);
  await login(1); assert.equal(await visible(),1,'admin owner can read an authorized candidate');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles.email,'private@example.invalid');
  await db.exec('reset role'); await db.exec(`update profiles set role='admin' where id='${id(2)}'`);
  await login(2);
  assert.equal(await visible(),0,'admin of another company cannot read this candidate');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  await db.exec('reset role'); await db.exec(`update profiles set role='company' where id in ('${id(1)}','${id(2)}')`);
  await login(2); assert.equal(await visible(),0);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await login(3); await db.exec("update student_profiles set contact_visibility='closed'");
  await login(1); assert.equal(await visible(),0);
  await db.exec('reset role'); await db.exec(`insert into applications values('${id(41)}','${id(31)}','${id(21)}','pending')`);
  await login(1); assert.equal(await visible(),1);
  await assert.rejects(db.exec(`update applications set student_id='${id(99)}'`),/permission denied/);
  await db.exec("update applications set status='accepted'");
  await db.exec('reset role'); await db.exec('delete from applications');
  await login(3); await db.exec("update student_profiles set contact_visibility='open'");
  await login(1); assert.equal(await visible(),1);
  await login(2); assert.equal(await visible(),0);
  // Launch offer: no payment gate, but open profiles must still consent.
  await db.exec('reset role');
  await db.exec(`create role service_role;
   alter table jobs add column is_active boolean default true, add column renewal_deadline timestamptz, add column title text default 'Vaga';
   alter table company_profiles add column company_name text default 'Empresa';
   create table notification_preferences(user_id uuid,email_enabled boolean,application_updates_enabled boolean,contact_requests_enabled boolean);
   create table notifications(id uuid default gen_random_uuid(),user_id uuid,event_key text unique,title text,message text,related_type text,related_id uuid,related_url text,action_label text,channels text[],email_status text,push_status text,is_read boolean default false);
   grant select on notifications to authenticated;
   grant update(is_read) on notifications to authenticated;
   create table company_candidate_actions(company_id uuid,student_id uuid,job_id uuid,action_type text,created_at timestamptz);
   grant insert on company_candidate_actions to authenticated;
   delete from candidate_contact_requests;
   insert into profiles values('${id(5)}','student','Second Candidate','second@example.invalid');
   insert into student_profiles(id,user_id,headline,location,desired_area,contact_visibility) values('${id(32)}','${id(5)}','Developer','Lisboa','IT','approval_required');
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20261001110626_free_company_launch_and_candidate_consent.sql',import.meta.url),'utf8'));
  await db.exec('revoke update on candidate_contact_requests from authenticated;grant update(status) on candidate_contact_requests to authenticated');
  await db.exec(await readFile(new URL('../supabase/migrations/20261001112946_atomic_candidate_contact_response.sql',import.meta.url),'utf8'));
  await db.exec('create trigger test_company_action before insert on company_candidate_actions for each row execute function guard_company_candidate_action()');
  await login(1);
  assert.equal(await visible(),0,'open profile is no longer automatic identity consent');
  const launchPreview=(await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(launchPreview.profiles,null);
  assert.equal(launchPreview.avatar_url,null);
  assert.equal(launchPreview.cv_url,undefined);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await assert.rejects(db.exec(`insert into company_candidate_actions(company_id,student_id,job_id,action_type) values('${id(11)}','${id(31)}','${id(21)}','accepted')`),/consent required/);
  const directory=(await db.query("select company_candidate_directory(null,'',1) as result")).rows[0].result;
  assert.equal(directory.total,2,'directory includes candidates without any calculated match');
  assert.ok(directory.items.every(item=>item.profiles===null));
  assert.equal((await db.query("select company_candidate_directory(null,'Lisboa',1) as result")).rows[0].result.total,1);
  await assert.rejects(db.query(`select company_candidate_directory('${id(22)}','',1)`),/not authorized/);
  await assert.rejects(db.query("select company_candidate_directory(null,'',0)"),/Invalid directory/);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(32)}','${id(21)}','pending')`);
  assert.equal((await db.query("select count(*)::int as n from notifications")).rows[0].n,1);
  await assert.rejects(db.exec("update candidate_contact_requests set status='accepted'"),/Only the candidate/);
  const pendingId=(await db.query("select id from candidate_contact_requests")).rows[0].id;
  await assert.rejects(db.query("select respond_candidate_contact_request($1,'accepted')",[pendingId]),/not authorized/);
  await login(5);
  assert.equal((await db.query("select respond_candidate_contact_request($1,'accepted') as status",[pendingId])).rows[0].status,'accepted');
  assert.equal((await db.query("select respond_candidate_contact_request($1,'rejected') as status",[pendingId])).rows[0].status,'accepted','a repeated or stale click cannot replace the recorded answer');
  assert.equal((await db.query("select count(*)::int as n from notifications")).rows[0].n,2);
  assert.equal((await db.query(`select is_read from notifications where user_id='${id(5)}'`)).rows[0].is_read,true);
  await assert.rejects(db.query("select company_candidate_directory(null,'',1)"),/Company account required/);
  await login(1); assert.equal(await visible(),1);
  await db.exec(`insert into company_candidate_actions(company_id,student_id,job_id,action_type) values('${id(11)}','${id(32)}','${id(21)}','accepted')`);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(32)}'::uuid]) snapshot`)).rows[0].snapshot.profiles.email,'second@example.invalid');
  await login(2); assert.equal(await visible(),0);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(32)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null);
  await login(5); await db.exec("update student_profiles set contact_visibility='closed'");
  await login(1); assert.equal(await visible(),0,'closing contact permissions still revokes consent access');
  await db.exec('reset role'); await db.exec(`insert into applications values('${id(42)}','${id(32)}','${id(21)}','pending')`);
  await login(1); assert.equal(await visible(),1,'an application still grants its company access');
  await login(2); assert.equal(await visible(),0);
  await db.exec('reset role');
  await db.exec(`insert into profiles(id,role,name,email) select ('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'student','Pagination candidate','pagination@example.invalid' from generate_series(100,130) n;
   insert into student_profiles(id,user_id,headline,contact_visibility) select ('00000000-0000-0000-0000-'||lpad((n+1000)::text,12,'0'))::uuid,('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'Pagination','approval_required' from generate_series(100,130) n;`);
  await login(1);
  const page1=(await db.query("select company_candidate_directory(null,'Pagination',1) as result")).rows[0].result;
  const page2=(await db.query("select company_candidate_directory(null,'Pagination',2) as result")).rows[0].result;
  assert.equal(page1.total,31); assert.equal(page1.items.length,24); assert.equal(page2.items.length,7);
  assert.equal(new Set([...page1.items,...page2.items].map(item=>item.id)).size,31);
  await db.exec('reset role');
  await db.exec(`insert into notification_preferences values('${id(3)}',true,true,false)`);
  await login(1);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`);
  assert.equal((await db.query(`select email_status from notifications where user_id='${id(3)}'`)).rows[0].email_status,'disabled','contact email preferences remain respected');
  await login(3);
  const refusalId=(await db.query(`select id from candidate_contact_requests where student_id='${id(31)}'`)).rows[0].id;
  assert.equal((await db.query("select respond_candidate_contact_request($1,'rejected') as status",[refusalId])).rows[0].status,'rejected');
  assert.equal((await db.query(`select is_read from notifications where user_id='${id(3)}'`)).rows[0].is_read,true);
  await login(1);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null,'rejecting a request never reveals an open profile');
  await assert.rejects(db.exec(`update candidate_contact_requests set status='pending' where student_id='${id(31)}'`),/Only the candidate/);
  await db.exec('reset role'); await db.exec(`update jobs set is_active=false where id='${id(21)}'`);
  await login(1);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`),/Vacancy unavailable/);
  // Expanded directory: all active visible candidates, independently of vacancies/matches.
  await db.exec(`reset role;create schema private;
    create table auth.users(id uuid primary key,banned_until timestamptz,email_confirmed_at timestamptz default now());
    insert into auth.users(id) select id from profiles;
    create table account_controls(user_id uuid);
    alter table profiles add column subscription_plan text default 'free', add column subscription_status text default 'inactive';
    alter table student_profiles add column if not exists main_role text, add column if not exists availability text, add column matching_preferences jsonb;
    create table matching_occupations(id uuid primary key,label text);
    create table skills(id uuid primary key,name text);
    create table student_skills(student_id uuid,skill_id uuid);
    insert into matching_occupations values('${id(500)}','Engenheiro de automação');
    update student_profiles set headline=null,matching_preferences='{"profession":"${id(500)}","levels":["senior"],"models":["remote","hybrid"],"skills":["Robótica"]}',availability='Imediata' where id='${id(31)}';
    insert into skills values('${id(501)}','PLC');insert into student_skills values('${id(31)}','${id(501)}');
    update auth.users set banned_until=now()+interval '1 day' where id='${id(100)}';
    insert into account_controls values('${id(101)}');
    update auth.users set email_confirmed_at=null where id='${id(102)}';
  `);
  const expanded=(await readdir('supabase/migrations')).find(name=>name.endsWith('_expand_candidate_directory.sql'));
  await db.exec(await readFile(`supabase/migrations/${expanded}`,'utf8'));
  await login(1);
  const search=async(filters={},query='',job=null,page=1)=>(await db.query('select company_candidate_search($1,$2,$3,$4) as data',[job,query,page,JSON.stringify(filters)])).rows[0].data;
  const all=await search();
  assert.equal(all.total,29,'closed, suspended, deleting and unconfirmed accounts are excluded; no headline is required');
  assert.ok(!all.items.some(item=>item.id===id(32)),'closed applicant is excluded from discovery despite existing company access');
  assert.equal((await search({},'',id(21))).total,all.total,'selecting a job does not limit results to its matches');
  const filtered=await search({location:'porto',seniority:'senior',work_model:'hybrid',availability:'Imediata',skill:'robó'},'automação');
  assert.equal(filtered.total,1);assert.equal(filtered.items[0].id,id(31));
  assert.equal(filtered.items[0].profiles,null);assert.equal(filtered.items[0].cv_url,undefined);
  assert.equal(filtered.items[0].bio,undefined);assert.equal(filtered.items[0].email,undefined);
  assert.equal((await search({skill:'PLC'})).total,1,'legacy skill links remain searchable');
  assert.equal((await search({work_model:'onsite'})).total,0);
  assert.equal((await search({location:'missing'})).total,0);
  assert.equal((await search({},'Pagination',null,2)).items.length,4);
  await assert.rejects(search({email:'private@example.invalid'}),/Invalid directory/);
  await assert.rejects(search({location:42}),/Invalid directory/);
  await assert.rejects(search({},'',id(22)),/not authorized/);
  await assert.rejects(search({},'',null,0),/Invalid directory/);
  await login(3);await assert.rejects(search(),/Company account required/);
  await login(4);await assert.rejects(search(),/Company account required/);
  await login(2);assert.equal((await search()).total,29,'company without matching candidates can browse');
  await db.exec(`reset role;insert into account_controls values('${id(2)}');`);
  await login(2);await assert.rejects(search(),/Company account required/);
  await db.exec(`reset role;delete from account_controls where user_id='${id(2)}';update private.candidate_directory_access set launch_free=false;`);
  await login(1);await assert.rejects(search(),/plan required/);
  await assert.rejects(db.query('select company_candidate_directory()'),/plan required/);
  await assert.rejects(db.query('update private.candidate_directory_access set launch_free=true'),/permission denied/);
  await db.exec(`reset role;update profiles set subscription_plan='premium',subscription_status='active' where id='${id(1)}';`);
  await login(1);assert.equal((await search()).total,29,'active paid plan can use directory after launch');
  await db.exec(`reset role;update profiles set subscription_status='canceled' where id='${id(1)}';`);
  await login(1);await assert.rejects(search(),/plan required/);
  // Profile consent works for a company with no active vacancies.
  await db.exec('reset role;update private.candidate_directory_access set launch_free=true;');
  const directMigration=(await readdir('supabase/migrations')).find(name=>name.endsWith('_company_profile_access_requests.sql'));
  await db.exec(await readFile(`supabase/migrations/${directMigration}`,'utf8'));
  await login(2);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(12)}','${id(31)}',null,'pending')`);
  const directId=(await db.query(`select id from candidate_contact_requests where company_id='${id(12)}' and job_id is null`)).rows[0].id;
  assert.equal((await search({skill:'PLC'})).items[0].contact_request_status,'pending');
  assert.equal((await search({skill:'PLC'})).items[0].profiles,null);
  const requestNotice=(await db.query('select message,related_url from notifications where related_id=$1',[directId])).rows[0];
  assert.ok(requestNotice.message.includes('perfil completo'));assert.ok(!requestNotice.message.includes('vaga'));
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(12)}','${id(31)}',null,'pending')`),/duplicate key/);
  await assert.rejects(db.exec(`update candidate_contact_requests set status='accepted' where id='${directId}'`),/Only the candidate/);
  await login(1);await assert.rejects(db.query("select respond_candidate_contact_request($1,'accepted')",[directId]),/not authorized/);
  await login(3);
  await db.query("select respond_candidate_contact_request($1,'accepted')",[directId]);
  await login(2);
  assert.equal((await search({skill:'PLC'})).items[0].profiles.email,'private@example.invalid');
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,1,'CV follows direct candidate consent');
  const answerNotice=(await db.query("select message,related_url from notifications where related_id=$1 and user_id=$2",[directId,id(2)])).rows[0];
  assert.equal(answerNotice.related_url,`/empresa/candidatos/${id(31)}`);assert.ok(answerNotice.message.includes('acesso ao perfil'));
  await login(1);assert.equal((await search({skill:'PLC'})).items[0].profiles,null,'other companies gain no access');
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}',null,'pending')`);
  const refusedId=(await db.query(`select id from candidate_contact_requests where company_id='${id(11)}' and job_id is null`)).rows[0].id;
  await login(3);await db.query("select respond_candidate_contact_request($1,'rejected')",[refusedId]);
  await login(1);assert.equal((await search({skill:'PLC'})).items[0].profiles,null);
  assert.equal((await search({skill:'PLC'})).items[0].contact_request_status,'rejected');
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}',null,'pending')`),/duplicate key/);
  await login(3);await db.exec("update student_profiles set contact_visibility='closed' where id='"+id(31)+"'");
  await login(2);assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0,'closed visibility revokes direct CV access');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(12)}','${id(32)}',null,'pending')`),/unavailable/);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(12)}','${id(1100)}',null,'pending')`),/unavailable/);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(1103)}',null,'pending')`),/not authorized/);
  await db.exec('reset role;update private.candidate_directory_access set launch_free=false;');
  await login(2);await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(12)}','${id(1103)}',null,'pending')`),/plan required/);
  await db.exec('reset role;set role anon');
  await assert.rejects(db.query("select company_candidate_directory(null,'',1)"),/permission denied/);
  await assert.rejects(db.query('select company_candidate_search()'),/permission denied/);
  await assert.rejects(db.query("select respond_candidate_contact_request($1,'accepted')",[pendingId]),/permission denied/);
 } finally { await db.close(); }
});
