import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('candidate consent, company isolation, CV and logo policies', async () => {
 const db = new PGlite();
 try {
  await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
  create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
  create function storage.foldername(text) returns text[] language sql as 'select string_to_array($1,''/'')';
  grant usage on schema public,auth,storage to authenticated;
  create table profiles(id uuid,role text,name text,email text);
  create table company_profiles(id uuid,user_id uuid);
  create table student_profiles(id uuid,user_id uuid,headline text,location text,desired_area text,seniority text,work_model text,talent_type text,contact_visibility text,cv_url text,bio text);
  create table jobs(id uuid,company_id uuid);
  create table ai_matches(student_id uuid,job_id uuid);
  create table applications(id uuid,student_id uuid,job_id uuid,status text);
  create table candidate_contact_requests(id uuid default gen_random_uuid(),company_id uuid,student_id uuid,job_id uuid,status text,message text,created_at timestamptz default now(),updated_at timestamptz default now());
  create table storage.buckets(id text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
  alter table student_profiles enable row level security;
  alter table storage.objects enable row level security;
  create function can_company_read_student_profile(uuid) returns boolean language sql as 'select true';
  create policy full_profiles on student_profiles for select to authenticated using(can_company_read_student_profile(id));
  create policy own_profiles on student_profiles for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
  create policy "Authenticated users can upload company logos" on storage.objects for insert to authenticated with check(bucket_id='company-logos');
  create policy "Authenticated users can update company logos" on storage.objects for update to authenticated using(bucket_id='company-logos');
  create policy "Authenticated users can delete company logos" on storage.objects for delete to authenticated using(bucket_id='company-logos');
  create policy logos_read on storage.objects for select to authenticated using(bucket_id='company-logos');
  grant all on all tables in schema public,storage to authenticated;
  insert into profiles values('${id(1)}','company','A','a@example.invalid'),('${id(2)}','company','B','b@example.invalid'),('${id(3)}','student','Candidate','private@example.invalid');
  insert into company_profiles values('${id(11)}','${id(1)}'),('${id(12)}','${id(2)}');
  insert into jobs values('${id(21)}','${id(11)}'),('${id(22)}','${id(12)}');
  insert into student_profiles values('${id(31)}','${id(3)}','Role','Porto','IT','senior','remote','professional','approval_required','${id(3)}/cv.pdf','Private biography');
  insert into ai_matches values('${id(31)}','${id(21)}');
  insert into storage.objects(bucket_id,name) values('student-cvs','${id(3)}/cv.pdf'),('company-logos','${id(12)}/logo.png');
  insert into storage.buckets(id,public) values('student-cvs',false),('cvs',false),('company-logos',true);
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20260929232747_protect_candidate_privacy.sql',import.meta.url),'utf8'));
  const migration = (await readdir(new URL('../supabase/migrations/',import.meta.url))).find(name=>name.endsWith('_allow_owned_company_candidate_reads.sql'));
  assert.ok(migration,'owned-company read migration must be present');
  await db.exec(await readFile(new URL(`../supabase/migrations/${migration}`,import.meta.url),'utf8'));
  const login = async n => db.exec(`reset role;set role authenticated;set request.test_user='${id(n)}';`);
  const visible = async () => (await db.query('select * from student_profiles')).rows.length;
  await login(1); assert.equal(await visible(),0);
  const preview = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(preview.headline,'Role'); assert.equal(preview.profiles,null); assert.equal(preview.bio,undefined); assert.equal(preview.cv_url,undefined);
  await db.exec('reset role');
  await db.exec(`update profiles set role='admin' where id='${id(1)}'; insert into profiles values('${id(4)}','admin','Unassociated admin','admin@example.invalid');`);
  await login(1);
  assert.equal(await visible(),0,'admin company owner still needs candidate consent');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null);
  await login(4);
  assert.equal(await visible(),0,'admin without a company gets no global candidate access');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  await db.exec('reset role'); await db.exec(`update profiles set role='company' where id='${id(1)}'`);
  await login(1);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(22)}','pending')`),/not authorized/);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','accepted')`),/Only the candidate/);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`);
  await assert.rejects(db.exec("update candidate_contact_requests set status='accepted'"),/Only the candidate/);
  await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(12)}/forged.png')`),/row-level security/);
  await db.exec(`insert into storage.objects(bucket_id,name) values('company-logos','${id(11)}/own.png')`);
  await db.exec(`update storage.objects set name='${id(12)}/edited.png' where name='${id(12)}/logo.png'`);
  assert.equal((await db.query(`select name from storage.objects where name='${id(12)}/logo.png'`)).rows.length,1);
  await login(3); await assert.rejects(db.exec(`update candidate_contact_requests set job_id='${id(22)}'`),/immutable/);
  await db.exec("update candidate_contact_requests set status='accepted'");
  await assert.rejects(db.exec("update candidate_contact_requests set status='rejected'"),/Invalid contact/);
  await login(1); assert.equal(await visible(),1);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,1);
  const full = (await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(full.profiles.email,'private@example.invalid');
  await db.exec('reset role'); await db.exec(`update profiles set role='admin' where id='${id(1)}'`);
  await login(1); assert.equal(await visible(),1,'admin owner can read an authorized candidate');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles.email,'private@example.invalid');
  await db.exec('reset role'); await db.exec(`update profiles set role='admin' where id='${id(2)}'`);
  await login(2);
  assert.equal(await visible(),0,'admin of another company cannot read this candidate');
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  await db.exec('reset role'); await db.exec(`update profiles set role='company' where id in ('${id(1)}','${id(2)}')`);
  await login(2); assert.equal(await visible(),0);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid])`)).rows.length,0);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await login(3); await db.exec("update student_profiles set contact_visibility='closed'");
  await login(1); assert.equal(await visible(),0);
  await db.exec('reset role'); await db.exec(`insert into applications values('${id(41)}','${id(31)}','${id(21)}','pending')`);
  await login(1); assert.equal(await visible(),1);
  await assert.rejects(db.exec(`update applications set student_id='${id(99)}'`),/permission denied/);
  await db.exec("update applications set status='accepted'");
  await db.exec('reset role'); await db.exec('delete from applications');
  await login(3); await db.exec("update student_profiles set contact_visibility='open'");
  await login(1); assert.equal(await visible(),1);
  await login(2); assert.equal(await visible(),0);
  // Launch offer: no payment gate, but open profiles must still consent.
  await db.exec('reset role');
  await db.exec(`create role service_role;
   alter table jobs add column is_active boolean default true, add column renewal_deadline timestamptz, add column title text default 'Vaga';
   alter table company_profiles add column company_name text default 'Empresa';
   create table notification_preferences(user_id uuid,email_enabled boolean,application_updates_enabled boolean,contact_requests_enabled boolean);
   create table notifications(id uuid default gen_random_uuid(),user_id uuid,event_key text unique,title text,message text,related_type text,related_id uuid,related_url text,action_label text,channels text[],email_status text,push_status text);
   grant select on notifications to authenticated;
   create table company_candidate_actions(company_id uuid,student_id uuid,job_id uuid,action_type text,created_at timestamptz);
   grant insert on company_candidate_actions to authenticated;
   delete from candidate_contact_requests;
   insert into profiles values('${id(5)}','student','Second Candidate','second@example.invalid');
   insert into student_profiles(id,user_id,headline,location,desired_area,contact_visibility) values('${id(32)}','${id(5)}','Developer','Lisboa','IT','approval_required');
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20261001110626_free_company_launch_and_candidate_consent.sql',import.meta.url),'utf8'));
  await db.exec('create trigger test_company_action before insert on company_candidate_actions for each row execute function guard_company_candidate_action()');
  await login(1);
  assert.equal(await visible(),0,'open profile is no longer automatic identity consent');
  const launchPreview=(await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot;
  assert.equal(launchPreview.profiles,null);
  assert.equal(launchPreview.avatar_url,null);
  assert.equal(launchPreview.cv_url,undefined);
  assert.equal((await db.query("select * from storage.objects where bucket_id='student-cvs'")).rows.length,0);
  await assert.rejects(db.exec(`insert into company_candidate_actions(company_id,student_id,job_id,action_type) values('${id(11)}','${id(31)}','${id(21)}','accepted')`),/consent required/);
  const directory=(await db.query("select company_candidate_directory(null,'',1) as result")).rows[0].result;
  assert.equal(directory.total,2,'directory includes candidates without any calculated match');
  assert.ok(directory.items.every(item=>item.profiles===null));
  assert.equal((await db.query("select company_candidate_directory(null,'Lisboa',1) as result")).rows[0].result.total,1);
  await assert.rejects(db.query(`select company_candidate_directory('${id(22)}','',1)`),/not authorized/);
  await assert.rejects(db.query("select company_candidate_directory(null,'',0)"),/Invalid directory/);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(32)}','${id(21)}','pending')`);
  assert.equal((await db.query("select count(*)::int as n from notifications")).rows[0].n,1);
  await assert.rejects(db.exec("update candidate_contact_requests set status='accepted'"),/Only the candidate/);
  await login(5); await db.exec("update candidate_contact_requests set status='accepted'");
  assert.equal((await db.query("select count(*)::int as n from notifications")).rows[0].n,2);
  await assert.rejects(db.query("select company_candidate_directory(null,'',1)"),/Company account required/);
  await login(1); assert.equal(await visible(),1);
  await db.exec(`insert into company_candidate_actions(company_id,student_id,job_id,action_type) values('${id(11)}','${id(32)}','${id(21)}','accepted')`);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(32)}'::uuid]) snapshot`)).rows[0].snapshot.profiles.email,'second@example.invalid');
  await login(2); assert.equal(await visible(),0);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(32)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null);
  await login(5); await db.exec("update student_profiles set contact_visibility='closed'");
  await login(1); assert.equal(await visible(),0,'closing contact permissions still revokes consent access');
  await db.exec('reset role'); await db.exec(`insert into applications values('${id(42)}','${id(32)}','${id(21)}','pending')`);
  await login(1); assert.equal(await visible(),1,'an application still grants its company access');
  await login(2); assert.equal(await visible(),0);
  await db.exec('reset role');
  await db.exec(`insert into profiles(id,role,name,email) select ('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'student','Pagination candidate','pagination@example.invalid' from generate_series(100,130) n;
   insert into student_profiles(id,user_id,headline,contact_visibility) select ('00000000-0000-0000-0000-'||lpad((n+1000)::text,12,'0'))::uuid,('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'Pagination','approval_required' from generate_series(100,130) n;`);
  await login(1);
  const page1=(await db.query("select company_candidate_directory(null,'Pagination',1) as result")).rows[0].result;
  const page2=(await db.query("select company_candidate_directory(null,'Pagination',2) as result")).rows[0].result;
  assert.equal(page1.total,31); assert.equal(page1.items.length,24); assert.equal(page2.items.length,7);
  assert.equal(new Set([...page1.items,...page2.items].map(item=>item.id)).size,31);
  await db.exec('reset role');
  await db.exec(`insert into notification_preferences values('${id(3)}',true,true,false)`);
  await login(1);
  await db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`);
  assert.equal((await db.query(`select email_status from notifications where user_id='${id(3)}'`)).rows[0].email_status,'disabled','contact email preferences remain respected');
  await login(3); await db.exec(`update candidate_contact_requests set status='rejected' where student_id='${id(31)}'`);
  await login(1);
  assert.equal((await db.query(`select company_candidate_snapshots(array['${id(31)}'::uuid]) snapshot`)).rows[0].snapshot.profiles,null,'rejecting a request never reveals an open profile');
  await assert.rejects(db.exec(`update candidate_contact_requests set status='pending' where student_id='${id(31)}'`),/Only the candidate/);
  await db.exec('reset role'); await db.exec(`update jobs set is_active=false where id='${id(21)}'`);
  await login(1);
  await assert.rejects(db.exec(`insert into candidate_contact_requests(company_id,student_id,job_id,status) values('${id(11)}','${id(31)}','${id(21)}','pending')`),/Vacancy unavailable/);
  await db.exec('reset role;set role anon');
  await assert.rejects(db.query("select company_candidate_directory(null,'',1)"),/permission denied/);
 } finally { await db.close(); }
});
