import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import {PGlite} from '@electric-sql/pglite';
const admin='10000000-0000-0000-0000-000000000001',student='20000000-0000-0000-0000-000000000001',company='30000000-0000-0000-0000-000000000001';
test('external jobs enforce registration, candidate role, expiry, source pause and leased atomic imports',async()=>{
 const db=new PGlite();try{
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';grant usage on schema auth,public to anon,authenticated,service_role;create table public.profiles(id uuid primary key,role text);grant select on public.profiles to authenticated,service_role;insert into auth.users values ('${admin}'),('${student}'),('${company}');insert into public.profiles values ('${admin}','admin'),('${student}','student'),('${company}','company');`);
  await db.exec(await readFile(new URL('../supabase/migrations/20261006161657_external_job_feed.sql',import.meta.url),'utf8'));
  await db.exec(`create function auth.jwt() returns jsonb language sql as 'select coalesce(nullif(current_setting(''request.test_jwt'',true),''''),''{}'')::jsonb';`);
  await db.exec(await readFile(new URL('../supabase/migrations/20261006162156_external_jobs_registered_candidates.sql',import.meta.url),'utf8'));
  await db.exec('set role service_role');
  await db.query('select configure_external_jobs($1,true,$2,true)',[admin,['fr']]);
  const lease=(await db.query('select claim_external_job_sync() as claim')).rows[0].claim.lease;
  assert.equal((await db.query('select claim_external_job_sync() as claim')).rows[0].claim.skipped,'cooldown');
  const rows=[{provider_id:'1',country_code:'FR',title:'Developer',company_name:'Example',description:'Private excerpt',location:'Paris',area:'IT',contract_type:null,source_url:'https://www.adzuna.fr/jobs/land/ad/1',created_at:new Date().toISOString()}];
  await assert.rejects(db.query('select finish_external_job_sync($1,$2,$3,0)',[admin,JSON.stringify(rows),[]]),/Stale import/);
  assert.equal((await db.query('select finish_external_job_sync($1,$2,$3,0) as count',[lease,JSON.stringify(rows),[]])).rows[0].count,1);
  await assert.rejects(db.query('select finish_external_job_sync($1,$2,$3,0)',[lease,JSON.stringify(rows),[]]),/Stale import/);
  await db.exec('reset role;set role anon');
  assert.equal((await db.query('select title from external_jobs')).rows.length,1);
  await assert.rejects(db.query('select * from external_job_details'),/permission denied/);
  await assert.rejects(db.query('select claim_external_job_sync()'),/permission denied/);
  await assert.rejects(db.query('select * from external_job_sync_state'),/permission denied/);
  await db.exec(`reset role;set role authenticated;select set_config('request.test_user','${company}',false)`);
  assert.equal((await db.query('select * from external_job_details')).rows.length,0);
  await assert.rejects(db.query('update external_job_sources set enabled=true'),/permission denied/);
  await db.exec(`select set_config('request.test_user','${student}',false)`);
  assert.equal((await db.query('select source_url from external_job_details')).rows.length,1);
  await db.query("select set_config('request.test_jwt',$1,false)",[JSON.stringify({is_anonymous:true})]);
  assert.equal((await db.query('select source_url from external_job_details')).rows.length,0);
  await db.query("select set_config('request.test_jwt',$1,false)",['{}']);
  await db.exec('reset role;set role service_role');
  await db.query('select configure_external_jobs($1,false,$2,true)',[admin,['fr']]);
  await db.exec('reset role;set role authenticated');
  assert.equal((await db.query('select * from external_job_details')).rows.length,0);
  assert.equal((await db.query('select * from external_jobs')).rows.length,0);
  await db.exec('reset role;set role service_role');
  await db.query('select configure_external_jobs($1,true,$2,true)',[admin,['fr']]);
  await db.exec("update external_jobs set expires_at=now()-interval '1 second'");
  await db.exec('reset role;set role authenticated');
  assert.equal((await db.query('select * from external_job_details')).rows.length,0);
  await db.exec("reset role;set role service_role;update external_job_sync_state set started_at=now()-interval '21 hours'");
  const second=(await db.query('select claim_external_job_sync() as claim')).rows[0].claim.lease;
  await db.query('select configure_external_jobs($1,false,$2,true)',[admin,['fr']]);
  assert.equal((await db.query('select finish_external_job_sync($1,$2,$3,0) as count',[second,JSON.stringify(rows),[]])).rows[0].count,0);
  assert.equal((await db.query('select status from external_job_sync_state')).rows[0].status,'cancelled');
  assert.equal((await db.query('select count(*)::int as n from external_job_settings_audit')).rows[0].n,4);
 }finally{await db.close();}
});
