import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { pg_trgm } from "@electric-sql/pglite/contrib/pg_trgm";
test("localized skill labels preserve canonical matching, visibility and write restrictions", async () => {
 const db=new PGlite({extensions:{pg_trgm}});
 const student='10000000-0000-0000-0000-000000000001', company='20000000-0000-0000-0000-000000000001',admin='30000000-0000-0000-0000-000000000001';
 const user=async id=>{await db.exec(`reset role;set role authenticated;select set_config('request.test_user','${id}',false)`);};
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
   create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
   grant usage on schema public,auth to anon,authenticated,service_role;
   create table public.profiles(id uuid primary key,role text);grant select on public.profiles to authenticated;
   create table public.student_profiles(id uuid);create table public.skills(name text);create table public.jobs(required_skills text[],preferred_skills text[]);
   insert into public.skills values('React');insert into public.profiles values('${student}','student'),('${company}','company'),('${admin}','admin');`);
  await db.exec(await readFile(new URL('../supabase/migrations/20261001145441_shared_profile_tags_and_country.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/20261001155614_curated_skill_catalog_and_moderation.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/20261001160415_indexed_tag_search.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/20261001180044_localized_esco_skills.sql',import.meta.url),'utf8'));
  await db.exec(`insert into public.profile_tag_translations select id,'de','Reakt Entwicklung','reakt entwicklung' from public.profile_tags where label='React'`);
  await user(company);
  const translated=(await db.query("select * from public.search_profile_tags_localized('entwicklung','de',20)")).rows;
  assert.equal(translated[0].label,'React'); assert.equal(translated[0].display_label,'Reakt Entwicklung');
  assert.equal((await db.query("select * from public.search_profile_tags_localized('%','de',20)")).rows.length,0);
  await assert.rejects(db.query("insert into public.profile_tag_translations select id,'fr','Test','test' from public.profile_tags"),/permission denied/);
  await user(student);
  await db.query("select public.ensure_profile_tag('React frontend')");
  const proposal=(await db.query("select id,status from public.profile_tags where label='React frontend'")).rows[0];
  await db.exec('reset role'); await db.query("insert into public.profile_tag_translations values($1,'de','Private Entwicklung','private entwicklung')",[proposal.id]); await user(student);
  assert.equal((await db.query("select * from public.search_profile_tags_localized('private entwicklung','de',20)")).rows[0].label,'React frontend');
  const target=(await db.query("select id from public.profile_tags where label='React'")).rows[0].id;
  assert.equal(proposal.status,'pending');
  assert.ok((await db.query("select * from public.search_profile_tags('frontend',20)")).rows.some(r=>r.label==='React frontend'));
  await assert.rejects(db.query("select created_by from public.profile_tags"),/permission denied/);
  await assert.rejects(db.query("update public.profile_tags set status='approved'"),/permission denied/);
  await assert.rejects(db.query("select public.moderate_profile_tag($1,'approve','pending',null)",[proposal.id]),/administradores/);
  await assert.rejects(db.query("select public.import_esco_profile_tags('[]','v1.2.1')"),/permission denied/);
  await user(company);
  assert.equal((await db.query("select * from public.search_profile_tags_localized('private entwicklung','de',20)")).rows.length,0);
  assert.equal((await db.query("select label from public.profile_tags where label='React frontend'")).rows.length,0);
  assert.equal((await db.query("select * from public.search_profile_tags('frontend',20)")).rows.length,0);
  await assert.rejects(db.query("select public.moderate_profile_tag($1,'approve','pending',null)",[proposal.id]),/administradores/);
  await user(admin);
  await db.query("select public.moderate_profile_tag($1,'alias','pending',$2)",[proposal.id,target]);
  await assert.rejects(db.query("select public.moderate_profile_tag($1,'approve','pending',null)",[proposal.id]),/estado mudou/);
  await user(company);
  assert.equal((await db.query("select public.ensure_profile_tag('React frontend') as label")).rows[0].label,'React');
  assert.equal((await db.query("select * from public.search_profile_tags('frontend',20)")).rows[0].label,'React');
  assert.equal((await db.query("select * from public.search_profile_tags('%',20)")).rows.length,0);
  assert.equal((await db.query("select * from public.search_profile_tags('',1000)")).rows.length,20);
  await user(student);await db.query("select public.ensure_profile_tag('Proposta para aprovar')");
  const approved=(await db.query("select id from public.profile_tags where label='Proposta para aprovar'")).rows[0].id;
  await user(admin);await db.query("select public.moderate_profile_tag($1,'approve','pending',null)",[approved]);
  await user(company);assert.equal((await db.query("select * from public.search_profile_tags('Proposta para aprovar',20)")).rows.length,1);
  await db.exec('reset role');
  const rows='[["11111111-1111-1111-1111-111111111111","Competência ESCO de teste"]]';
  await db.query("select public.import_esco_profile_tags($1,'v1.2.1')",[rows]);await db.query("select public.import_esco_profile_tags($1,'v1.2.1')",[rows]);
  assert.equal((await db.query("select count(*) as total from public.profile_tags where source='esco'")).rows[0].total,1);
  const esco=(await db.query("select id from public.profile_tags where source='esco'")).rows[0].id;
  await user(admin);await assert.rejects(db.query("select public.moderate_profile_tag($1,'alias','approved',$2)",[esco,target]),/conceitos ESCO distintos/);
  await db.query("select public.moderate_profile_tag($1,'unlink','rejected',null)",[proposal.id]);
  await user(company);assert.equal((await db.query("select * from public.search_profile_tags('frontend',20)")).rows.length,0);
  await db.exec('reset role');assert.equal((await db.query('select count(*) as count from private.profile_tag_reviews')).rows[0].count,3);
  await db.exec('set role anon');await assert.rejects(db.query("select * from public.search_profile_tags_localized('entwicklung','de',20)"),/permission denied/);await assert.rejects(db.query("select * from public.search_profile_tags('',20)"),/permission denied/);
 } finally {await db.close();}
});
