import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('recruitment writes enforce role, vacancy ownership, consent and deduplication',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.test_user'',true),'''')::uuid';
 grant usage on schema public,auth to authenticated;
 create table profiles(id uuid primary key,role text);
 create table company_profiles(id uuid primary key,user_id uuid);
 create table student_profiles(id uuid primary key,user_id uuid,contact_visibility text);
 create table jobs(id uuid primary key,company_id uuid,is_active boolean);
 create table ai_matches(student_id uuid,job_id uuid);
 create table candidate_contact_requests(company_id uuid,student_id uuid,job_id uuid,status text);
 create table applications(id uuid default gen_random_uuid() primary key,job_id uuid,student_id uuid,status text default 'pending',created_at timestamptz default now(),unique(job_id,student_id));
 create table company_candidate_actions(id uuid default gen_random_uuid(),company_id uuid,student_id uuid,job_id uuid,action_type text,created_at timestamptz default now());
 create table candidate_actions(id uuid default gen_random_uuid(),student_id uuid,job_id uuid,action_type text,created_at timestamptz default now());
 grant all on all tables in schema public to authenticated;
 alter table applications enable row level security;
 create policy candidate_insert on applications for insert to authenticated with check(exists(select 1 from student_profiles s where s.id=applications.student_id and s.user_id=auth.uid()));
 create policy app_select on applications for select to authenticated using(exists(select 1 from student_profiles s where s.id=applications.student_id and s.user_id=auth.uid()) or exists(select 1 from jobs j join company_profiles c on c.id=j.company_id where j.id=applications.job_id and c.user_id=auth.uid()));
 create policy app_update on applications for update to authenticated using(exists(select 1 from jobs j join company_profiles c on c.id=j.company_id where j.id=applications.job_id and c.user_id=auth.uid()));
 alter table company_candidate_actions enable row level security;
 create policy own_company on company_candidate_actions for all to authenticated using(exists(select 1 from company_profiles c where c.id=company_candidate_actions.company_id and c.user_id=auth.uid())) with check(exists(select 1 from company_profiles c where c.id=company_candidate_actions.company_id and c.user_id=auth.uid()));
 insert into profiles values('${id(1)}','company'),('${id(2)}','company'),('${id(3)}','student'),('${id(4)}','student');
 insert into company_profiles values('${id(11)}','${id(1)}'),('${id(12)}','${id(2)}');
 insert into student_profiles values('${id(31)}','${id(3)}','approval_required'),('${id(32)}','${id(4)}','closed');
 insert into jobs values('${id(21)}','${id(11)}',true),('${id(22)}','${id(12)}',true),('${id(23)}','${id(11)}',false),('${id(24)}','${id(11)}',true);
 insert into ai_matches values('${id(31)}','${id(21)}'),('${id(31)}','${id(24)}');
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/20260929232748_validate_recruitment_actions.sql',import.meta.url),'utf8'));
 const login=async n=>db.exec(`reset role;set role authenticated;set request.test_user='${id(n)}';`);
 const apply=job=>db.exec(`insert into applications(job_id,student_id) values('${id(job)}','${id(31)}')`);
 const action=(job,type='accepted',student=31)=>db.exec(`insert into company_candidate_actions(company_id,student_id,job_id,action_type) values('${id(11)}','${id(student)}','${id(job)}','${type}')`);
 await login(3);
 await assert.rejects(db.exec(`insert into applications(job_id,student_id,status) values('${id(21)}','${id(31)}','accepted')`),/permission denied/);
 await assert.rejects(apply(23),/not accepting/);
 await assert.rejects(db.exec(`insert into applications(job_id,student_id) values('${id(21)}','${id(32)}')`),/must be submitted/);
 await apply(21);await assert.rejects(apply(21),/duplicate key/);
 assert.equal((await db.query('select status from applications')).rows[0].status,'pending');
 await db.exec("update applications set status='accepted'");
 assert.equal((await db.query('select status from applications')).rows[0].status,'pending');
 await login(1);
 await assert.rejects(action(22),/not authorized/);
 await assert.rejects(action(21,'invented'),/not authorized/);
 await assert.rejects(action(21,'shortlisted',32),/not associated/);
 await action(21); await assert.rejects(action(21),/duplicate key/);
 await assert.rejects(db.exec("update company_candidate_actions set action_type='shortlisted'"),/permission denied/);
 await assert.rejects(action(24),/consent required/);
 await action(24,'shortlisted');
 await db.exec("update applications set status='accepted'");
 await login(3);
 assert.deepEqual((await db.query('select job_id,status from applications')).rows,[{job_id:id(21),status:'accepted'}], 'candidate sees the decision recorded by their vacancy owner');
 await login(4);
 assert.equal((await db.query('select * from applications')).rows.length,0,'another candidate cannot see this application');
 await login(1);
 await assert.rejects(db.exec("update applications set status='invented'"),/not authorized/);
 await assert.rejects(db.exec(`update applications set student_id='${id(32)}'`),/immutable/);
 await login(2);
 assert.equal((await db.query('select * from applications')).rows.length,0);
 await assert.rejects(action(21),/not authorized/);
 await db.exec('reset role');
 await db.exec(`insert into candidate_contact_requests values('${id(11)}','${id(31)}','${id(21)}','accepted')`);
 await login(1); await assert.rejects(action(24),/consent required/);
 await db.exec('reset role');await db.exec(`insert into candidate_contact_requests values('${id(11)}','${id(31)}','${id(24)}','accepted')`);
 await login(1);await action(24);
 await db.exec("delete from company_candidate_actions where action_type='accepted'");
 await db.exec('reset role');await db.exec("update student_profiles set contact_visibility='closed'");
 await login(1);await assert.rejects(action(24),/consent required/);await action(21);
 await login(3);
 await assert.rejects(db.exec(`insert into candidate_actions(student_id,job_id,action_type) values('${id(31)}','${id(21)}','applied')`),/Invalid candidate/);
 await db.exec(`insert into candidate_actions(student_id,job_id,action_type) values('${id(31)}','${id(21)}','saved')`);
 await assert.rejects(db.exec(`insert into candidate_actions(student_id,job_id,action_type) values('${id(31)}','${id(21)}','saved')`),/duplicate key/);
 await assert.rejects(db.exec(`insert into candidate_actions(student_id,job_id,action_type) values('${id(31)}','${id(23)}','ignored')`),/unavailable/);
 } finally {await db.close();}
});
