"use client";
import { LText, useI18n } from "@/lib/i18n/client";

import Link from "@/lib/i18n/link";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
import {passwordRecoveryError} from "@/lib/password-recovery";
export default function Page(){
 const {locale}=useI18n();
 const [ready,setReady]=useState(false);const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [done,setDone]=useState(false);
 useEffect(()=>{let active=true; const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(active && event==="PASSWORD_RECOVERY")setReady(true);});supabase.auth.getSession().then(({data})=>{if(active && data.session)setReady(true);});return()=>{active=false;subscription.unsubscribe();};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!ready)return;if(password!==confirm){setMessage("As palavras-passe não coincidem.");return;}setBusy(true);setMessage("");try{const {error}=await supabase.auth.updateUser({password});if(error){const feedback=passwordRecoveryError(error,locale);setMessage(feedback.message);if(feedback.needsNewLink)setReady(false);return;}setDone(true);setPassword("");setConfirm("");setMessage("Palavra-passe atualizada. Inicia sessão com a nova palavra-passe.");await supabase.auth.signOut().catch(()=>undefined);}catch{setMessage("Não foi possível ligar ao serviço.");}finally{setBusy(false);}}
 return <main className="mx-auto max-w-md px-6 py-20"><h1 className="text-3xl font-bold"><LText text={"Definir nova palavra-passe"} /></h1>{!ready && <p className="mt-5"><LText text={"Abre a ligação enviada por email. Se expirou, "} /><Link className="underline" href="/recuperar-acesso"><LText text={"pede uma nova ligação"} /></Link>.</p>}{ready&&!done&&<form onSubmit={submit} className="mt-6 space-y-4"><label htmlFor="new-password"><LText text={"Nova palavra-passe (mínimo 6 caracteres)"} /></label><input id="new-password" autoComplete="new-password" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border p-3"/><label htmlFor="confirm-password"><LText text={"Repetir palavra-passe"} /></label><input id="confirm-password" autoComplete="new-password" type="password" minLength={6} required value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-xl border p-3"/><button disabled={busy} className="rounded-full bg-[#07111F] px-6 py-3 text-white"><LText text={busy?"A guardar…":"Guardar palavra-passe"} /></button></form>}<p role="status" className="mt-5"><LText text={message} /></p><Link href="/login" className="mt-5 inline-block underline"><LText text={"Voltar ao login"} /></Link></main>;
}
